### ISSUE TITLE
remarkable has been moved to markdown-it

### ISSUE THREAD

**Issue by geyang** [browniefed/babel-plugin-markdown-react#5]
Hi @browniefed 

Thanks for building this plugin! Before this plugin I was using multi-line ES6 strings :P now I don't have to!

The remarkable parser has been renamed to markdown-it by it's main contributor after a split. Purina is super dedicates and is very active in engaging with the common mark standard. It would be nice to follow him. 

Would it be possible to move this plugin to markdown-it? I can submit a PR if your time is constrained.

Ge

**Comment by browniefed** [comment]
This is a really old plugin, and was written for Babel v5. Haven't even tested it on Babel 6 yet.

If you'd like to submit a PR and make sure it works with Babel 6 that'd be great, especially as I do not use this plugin.

**Comment by geyang** [comment]
Ah I see:) Then I might need to read through and assess.

Why are you not using this? What are the limitations?

**Comment by browniefed** [comment]
It shouldn't be that bad actually, all it does is look for a specific React Component in the AST and then transpile it's children to React.

I don't use it because I wrote it for a project then ended up not deciding to do that project anymore.

Main limitation is that Markdown is very whitespace sensitive, so it does it's best to strip all leading whitespace. So things technically need to be on the same line and then it'll all work. 

Overall it's an okay plugin, but there are others that might be better? Not sure.
